Repository Chenyme/Linux-Do-Wiki, pull requests merged in 2024-07, with the labels that each got.

#17 【新增】 文档历史页面更新记录页面 【改进】README 页面的感谢部分内容
  .gitignore
  README.md
  package-lock.json
  src/pages/History/2024-07-22.mdx
  src/pages/History/2024-07-23.mdx
  src/pages/History/2024-07-24.mdx
  src/pages/History/_meta.json
  src/pages/_meta.json
Labels: 【改进】, 【新增】, 【重要】

#16 【新增】DeepLX页面的使用方式内容
  public/deeplx_use4.png
  src/pages/DeepLX/deeplx.mdx
Labels: 【新增】

#18 【新增】Wiki使用说明（index）页面的 页尾Linux Do logo图片 现支持跟随主题切换 Closes #14
  README.md
  components/LinuxDoLogoWithThemes.js
  public/linuxdo_logo_with_dark_text.png
  public/linuxdo_logo_with_light_text.png
  src/pages/index.mdx
Labels: 【修复】, 【新增】

#24 【修复】Wiki共建荣誉榜页面的贡献者列表与预览列表在移动端表现不一致的问题 Closes #19
  src/pages/honor.mdx
Labels: 【修复】

#25 【修复】通配子域名页面的文本格式问题 Link #22
  src/pages/Oaifree/every.mdx
Labels: 【修复】

#30 【改进】：Steps组件序号从0开始 Link #28
  src/pages/LinuxDo/level.mdx
  styles/ExtraStyle.module.css
Labels: 【改进】

#35 【新增】Fuclaude docker-compose 部署方式
  src/pages/Fuclaude/fuclaude.mdx
Labels: 【新增】

#37 【新增】提供基础性网络服务，现已支持从 linux.do 获取各类数据
  Dockerfile
  package-lock.json
  package.json
  server.js
  service/web/httpService.js
  service/web/linuxdoAboutDataService.js
  service/web/linuxdoUserDataService.js
Labels: 【新增】, 【建设性】, 【重要】

#40 【改进】部分内容汉化
  components/ScrollToTop.js
  theme.config.jsx
Labels: 【改进】

#41 【新增】Fuclaude 通配子域名的支持和说明 【修复】新玩具 Fuclaude页面的更多探索表头问题
  src/pages/Fuclaude/_meta.json
  src/pages/Fuclaude/every.mdx
  src/pages/Fuclaude/fuclaude.mdx
Labels: 【修复】, 【新增】
