Repository Chenyme/Linux-Do-Wiki, pull requests merged in 2024-08, with the labels that each got.

#49 【改进】登录页样式微调，部分汉化
  components/Login.module.css
  components/loginloading.module.css
  src/pages/login.js
  theme.config.jsx
Labels: 【改进】

#46 【改进】/LinuxDo社区/基本信息&社区梗百科 两个页面 为提到的用户添加LinuxDoUserCard展示
  src/pages/LinuxDo/code.mdx
  src/pages/LinuxDo/info.mdx
Labels: 【改进】

#53 【改进】优化荣誉榜卡片显示样式，修复链接错误 Close #51
  components/Card.module.css
  components/GoldCard.module.css
  src/pages/Fuclaude/fuclaude.mdx
Labels: 【修复】, 【改进】

#58 【新增】赛博艺术目录（Linux Do Wiki 艺术组件精选集页面、CSS 折纸艺术展页面）
  components/pages/encyclopedia/cyber-art/css-art/Camera.module.css
  components/pages/encyclopedia/cyber-art/css-art/CssArtContainer.js
  components/pages/encyclopedia/cyber-art/css-art/Egg.module.css
  components/pages/encyclopedia/cyber-art/css-art/Hamburger.module.css
  components/pages/encyclopedia/cyber-art/css-art/Linuxdo.module.css
  components/pages/encyclopedia/cyber-art/css-art/Orizuru.module.css
  src/pages/encyclopedia/_meta.json
  src/pages/encyclopedia/cyber-art/CSS.mdx
  src/pages/encyclopedia/cyber-art/Linux-Do-Wiki-component.mdx
  src/pages/encyclopedia/cyber-art/_meta.json
Labels: 【新增】

#59 【改进】 user3.mdx
  src/pages/encyclopedia/user/user3.mdx
Labels: 【改进】

#60 【新增】打印div区域并下载图片功能组件
  components/cards/LinuxdoUserCard/LinuxdoUserCard.js
  components/common/Printer.js
  package-lock.json
  package.json
  src/pages/test/PrinterTest.mdx
  src/pages/test/_meta.json
Labels: 【新增】

#63 【更正】AFF 页面的 AFF规则变更
  src/pages/encyclopedia/cant/AFF.mdx
Labels: 【更正】
